CodeDemo/Controllers/RegisterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeDemo.Controllers
{
    public class RegisterController : Controller
    {
        WritterManager wm = new WritterManager(new EfWriterRepository());

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Writer p)
        {
            WriterValidator wv = new WriterValidator();
            ValidationResult result = wv.Validate(p);
            if(result.IsValid)
            {
                p.WriterStatus = true;
                p.WriterAbout = "Deneme Test";
                wm.TAdd(p);
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

CodeDemo/Views/Register/Index.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script src="~/lib/jquery/dist/jquery.js"></script>

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Yazar Kayıt Sayfası</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                @using (Html.BeginForm("Index", "Register", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom01">Adınız Soyadınız</label>

                            @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger"} )
                            @*<input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom02">Mail Adresi</label>

                            @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterMail, "", new { @class = "text-danger" })
                            @*<input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Şifre</label>

                            @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @class = "text-danger" })
                            @*<input type="password" class="form-control" id="password1" name="WriterPassword" placeholder="" required="">*@
                        </div>
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword2 mb-2">Görsel Dosya Yolu</label>

                            @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterImage, "", new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="password2" name="WriterImage" placeholder="" required="">*@
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Kayıt Ol</button>
                    <p>
                        <a href="#" id="btn1">Tüm şartları okudum, kabul ediyorum.</a>
                    </p>
                }

            </div>
        </div>
    </div>
    <br />
    <script>
        $('#btn1').click(function () {
            swal("Site Kabul Şartları","Sitemizde verdiğiniz mail adresi üzerinden bilgi ve haber e-postaları spam ölçüsüne varmadan gönderilmeye devam edilecektir."
                + "Eğer e - posta bülteninden çıkmak isterseniz mail ileti dizisini durdurabilirsiniz.Şifre ve mail adresleriniz şifrelenmiş formatta"
                + "herhangi bir kullanıcının görmeyeceği şekilde veri tabanlarımızda saklanmaktadır.");
        });
    </script>
</section>